name: Tests

on:
  push:

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # See https://github.com/actions/runner-images#available-images
        os: [ubuntu-latest]
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.5.18"

      - name: Setup zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0-dev.2571+01081cc8e
          cache: true

      - name: Setup wasmtime
        uses: jcbhmr/setup-wasmtime@v2
        with:
          wasmtime-version: v28.0.0
          cache: true

  test:
    runs-on: ${{ matrix.os }}
    needs: [setup]
    strategy:
      matrix:
        # See https://github.com/actions/runner-images#available-images
        os: [ubuntu-latest]
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          just create

      - name: Clean environment
        run: |
          just clean

      - name: Run tests
        run: |
          just test
